In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

C:\Users\chait\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\chait\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\chait\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\chait\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passi

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8156, 8668, 5658, 5530], [8156, 8668, 5658, 3674], [8156, 8095, 5658, 1430], [2203, 323, 5772, 4949, 3637], [2203, 323, 5772, 4949, 2670], [7214, 8156, 8109, 5658, 9174], [4948, 2451, 8208, 4949]]



### Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [9]:
sent_length=5
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0 8156 8668 5658 5530]
 [   0 8156 8668 5658 3674]
 [   0 8156 8095 5658 1430]
 [2203  323 5772 4949 3637]
 [2203  323 5772 4949 2670]
 [7214 8156 8109 5658 9174]
 [   0 4948 2451 8208 4949]]


In [10]:
dim=100

In [11]:

model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 5, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[-0.02179047  0.00451597  0.02547019 -0.02874999 -0.00440979
   -0.00799952  0.02258307 -0.03023667  0.04605336  0.02770117]
  [ 0.02737219  0.04902586  0.00012345  0.02728805 -0.03047475
    0.03679718  0.03635273  0.04694027  0.01020405 -0.03539884]
  [ 0.03033706  0.03766257  0.00697362 -0.00459355  0.04015059
    0.02912371  0.04056997 -0.01127787 -0.04491385 -0.01244863]
  [-0.0281494   0.01682511 -0.02206615  0.00680687 -0.0144984
    0.00723274 -0.03236369 -0.04074169 -0.00062448  0.01143988]
  [-0.04486392  0.0036182   0.00361699 -0.0294296  -0.03529109
    0.01741249  0.00307839  0.0328852   0.02246037  0.0214335 ]]

 [[-0.02179047  0.00451597  0.02547019 -0.02874999 -0.00440979
   -0.00799952  0.02258307 -0.03023667  0.04605336  0.02770117]
  [ 0.02737219  0.04902586  0.00012345  0.02728805 -0.03047475
    0.03679718  0.03635273  0.04694027  0.01020405 -0.03539884]
  [ 0.03033706  0.03766257  0.00697362 -0.00459355  0.04015059
    0.02912371  0.04056997 -0.01127787 -0.04491

In [14]:

embedded_docs[0]

array([   0, 8156, 8668, 5658, 5530])

In [15]:

print(model.predict(embedded_docs)[0])

[[-0.02179047  0.00451597  0.02547019 -0.02874999 -0.00440979 -0.00799952
   0.02258307 -0.03023667  0.04605336  0.02770117]
 [ 0.02737219  0.04902586  0.00012345  0.02728805 -0.03047475  0.03679718
   0.03635273  0.04694027  0.01020405 -0.03539884]
 [ 0.03033706  0.03766257  0.00697362 -0.00459355  0.04015059  0.02912371
   0.04056997 -0.01127787 -0.04491385 -0.01244863]
 [-0.0281494   0.01682511 -0.02206615  0.00680687 -0.0144984   0.00723274
  -0.03236369 -0.04074169 -0.00062448  0.01143988]
 [-0.04486392  0.0036182   0.00361699 -0.0294296  -0.03529109  0.01741249
   0.00307839  0.0328852   0.02246037  0.0214335 ]]


In [16]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

Num GPUs Available:  0


In [17]:
tf.config.experimental.list_physical_devices('GPU') 

[]